apiVersion: apps/v1
kind: Deployment
metadata:
  name: argonauts-todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: 154647635698.dkr.ecr.ap-southeast-1.amazonaws.com/argonauts:latest
        ports:
        - containerPort: 80